# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8943a8cc7f2ffd466fd04b101f63a77e183e976c71caa2390b3ae85919c083abb4ad55665a6ee1708699bd18647fd59da0b87898b9a841faf6508d4a463de40d

test:
  secret_key_base: 60c1fa79eb25e10637eccf9732acafac3280f819cf67f77f15145deb886251a7f1d59fb2c0ac44db83299eacbb17c882955e8da0322aeb49e4888353072470f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
